pool:
  name: Azure Pipelines
  demands: maven

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'

- task: Snyk.snyk-security-scan.custom-build-release-task.SnykSecurityScan@1
  displayName: 'Snyk scan for open source vulnerabilities'
  inputs:
    serviceConnectionEndpoint: 'Snyk Connection'
    failOnIssues: false


- task: ManualValidation@0
  inputs:
    notifyUsers: 'a.poosa@reply.it'
    instructions: 'continue?'
    onTimeout: reject
- task: Maven@4
  displayName: 'Maven pom.xml'
  inputs:
    goals: 'deploy -s settings.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: target
  condition: succeededOrFailed()
